# Generated by Django 5.0.7 on 2024-07-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_coordinator_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
