# Generated by Django 5.0.7 on 2024-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_coordinator_delete_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
