# Generated by Django 5.0.7 on 2024-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_gpa_student_age_student_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
