# Generated by Django 5.0.7 on 2024-08-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_subject_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('give_medal', 'Can give medals')]},
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
